version: '3.8'

services:
  django:
    build:
      context: ./django_server
    volumes:
      - ./django_server:/app
      - media_volume:/app/media
    network_mode: host
    environment:
      - DJANGO_SETTINGS_MODULE=smart_home.settings

  bot:
    build:
      context: ./bot
    volumes:
      - ./bot:/app
      - media_volume:/app/media
    network_mode: host

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: ./django_server
    command: celery -A smart_home worker --loglevel=info
    volumes:
      - ./django_server:/app
    depends_on:
      - redis
      - django

  celery-beat:
    build: ./django_server
    command: celery -A smart_home beat --loglevel=info
    volumes:
      - ./django_server:/app
    depends_on:
      - redis
      - django
      - celery

volumes:
  media_volume: