version: '3.8'

services:
  django:
    build:
      context: ./django_server
    volumes:
      - ./django_server:/app
    network_mode: host
    environment:
      - DJANGO_SETTINGS_MODULE=smart_home.settings

  bot:
    build:
      context: ./bot
    volumes:
      - ./bot:/app
    network_mode: host

#  celery:
#      build: ./celery
#      command: celery -A celery.celery_app worker --loglevel=info
#      volumes:
#        - ./django_server:/app
#      depends_on:
#        - redis
#        - django
#
#  celery-beat:
#    build: ./celery
#    command: celery -A celery.celery_app beat --loglevel=info
#    volumes:
#      - ./django_server:/app
#    depends_on:
#      - redis
#      - django
#      - celery
#
  redis:
    image: redis:latest
    network_mode: host