# Generated by Django 5.1.7 on 2025-03-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LightSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField()),
                ("days", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
