# Generated by Django 5.1.7 on 2025-03-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_lightschedule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lightschedule",
            options={
                "ordering": ["time"],
                "verbose_name": "Расписание света",
                "verbose_name_plural": "Расписания света",
            },
        ),
        migrations.AlterField(
            model_name="lightschedule",
            name="days",
            field=models.JSONField(
                default=list,
                help_text="Список дней, когда должно срабатывать расписание",
                verbose_name="Дни недели",
            ),
        ),
        migrations.AlterField(
            model_name="lightschedule",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Включено ли это расписание",
                verbose_name="Активно",
            ),
        ),
        migrations.AlterField(
            model_name="lightschedule",
            name="time",
            field=models.TimeField(verbose_name="Время срабатывания"),
        ),
    ]
