# Generated by Django 5.1.7 on 2025-04-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "devices",
            "0003_alter_lightschedule_options_alter_lightschedule_days_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lightschedule",
            options={},
        ),
    ]
