# Generated by Django 5.1.7 on 2025-04-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_alter_lightschedule_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField(verbose_name="Время срабатывания")),
                ("days", models.JSONField(default=list, verbose_name="Дни недели")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="lightschedule",
            name="days",
            field=models.JSONField(default=list, verbose_name="Дни недели"),
        ),
        migrations.AlterField(
            model_name="lightschedule",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
    ]
